/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Student {
    constructor() {
        this.stu_id = undefined;
        this.stuName = "0";
        this.stuSex = undefined;
        this.stuBir = undefined;
    }

    setStu_id(stu_id) {
        this.stu_id = stu_id;
    }

    getStu_id() {
        return this.stu_id;
    }

    setStuName(stuName) {
        this.stuName = stuName;
    }

    getStuName() {
        return this.stuName;
    }

    setStuSex(stuSex) {
        this.stuSex = stuSex;
    }

    getStuSex() {
        return this.stuSex;
    }

    setStuBir(stuBir) {
        this.stuBir = stuBir;
    }

    getStuBir() {
        return this.stuBir;
    }
}

Student.className = 'Student';

export {Student}